version: "3.9"

services:
  app:
    build: .
    container_name: backend_app
    ports:
      - "3000:3000"
    env_file:
      - .env
    # Dev mode: mount code từ host vào container
    volumes:
      - .:/app
      # - /app/node_modules
    